/* AUTO-GENERATED by build/generate-fallbacks.ts — do not edit by hand. */
export const FALLBACKS = {
  "borderDefault": "#e7e5e4",
  "textPrimary": "#1c1917",
  "textInverse": "#fafaf9",
  "bgSurface": "#ffffff"
} as const;

export type FallbackKey = keyof typeof FALLBACKS;
