/* AUTO-GENERATED by build/generate-fallbacks.ts — do not edit by hand. */
export const FALLBACKS = {
  "borderDefault": "#d9e0df",
  "textPrimary": "#15110b",
  "textInverse": "#f0f7f5",
  "bgSurface": "#ffffff",
  "inputBgDefault": "#ffffff",
  "inputBgDisabled": "#e9f1ef",
  "inputBgReadonly": "#f0f7f5",
  "inputBorderDefault": "#d9e0df",
  "inputBorderHover": "#909396",
  "inputBorderFocus": "#514ecf",
  "inputBorderInvalid": "#b22128",
  "inputBorderWarn": "#935f17",
  "inputTextDefault": "#15110b",
  "inputTextDisabled": "#909396",
  "inputTextReadonly": "#27231d",
  "inputTextPlaceholder": "#909396",
  "inputLabelDefault": "#27231d",
  "inputLabelRequired": "#b22128",
  "inputLabelFloatBg": "#ffffff",
  "inputMessageHelper": "#636568",
  "inputMessageError": "#b22128",
  "inputMessageWarn": "#935f17",
  "inputIconDefault": "#74777a",
  "inputIconInvalid": "#b22128",
  "inputIconWarn": "#935f17",
  "inputIconValidating": "#514ecf"
} as const;

export type FallbackKey = keyof typeof FALLBACKS;
